# Generated by Django 5.0.4 on 2024-07-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_categorymodel_task_and_more'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
    ]
